<template>
    <div class="individual-work-page-container">
       
        <b-container  class="work-session-backgroundcolor">
            <b-row>
                <b-col> <h3>hardworking circuit #1.3    勤力電路#1.3 </h3> </b-col>
            </b-row>
            <b-row>
                <b-col>     
                    <b-img  src="~/assets/images/hardworking-circuit-1p3sketch-03.svg" fluid > </b-img>
                    <figcaption class="figure-caption"> refined conceptual schematic diagram </figcaption>
                </b-col>
                
            </b-row>
            <b-row>
                
                <b-col md='9' order="1" order-md="2"> 
                    <p>hardworking circuit#1 is a realization of a schema of monotonous, repetitive circuit, using as many units as possible of relay switch to bridge up the 
                        sequential extension of cables, merely for the purpose of electricity connection
                    </p>

                </b-col>

                <b-col md="3"> 
                    <p> electronics 
                        <br>
                        2018
                    </p>                        
                    
                </b-col>
            </b-row>

            <b-row>
                <b-col>
                    <h4> The Initiation of making hardworking circuit #1.3 </h4> 
                    <p>
                        My work is invoked by my dissatisfaction with the overly spectacular appearance and total black-boxing of the algorithm and internal mechanisms in many media art works nowadays.
                        <br>Trained in a media art curriculum, I have a strong, even desperate, urge to maximize the potential of tools and raw materials in my hands, to push them in order to feel their limits. “How dumb can an electronic circuit function?” This question has always been lingering in my mind. Conventions of circuit design predicate primarily upon functionality and economic return. In response, in hardworking circuit #1, I have created an overtly excessive, and almost unnecessary circuit system, just to turn on some LED lights.
                        <br>I begin with plotting a schema of monotonous, repetitive circuit, using as many units as possible of relay switch to bridge up the sequential extension of cables, merely for the purpose of electricity connection. As I advance the connections and reach the 50th relay switch, the intensifying resistance of the growing cables and disorder in the relay switch cause the whole system to break down. Forced to stop by the circuit I have made, I review the ‘paper concept’ to reconsider what has happened by calculation, measurement and analysis, followed by a series of trial and error. Numbers and hardware – cold and inhuman they are – tell me a lot: why the system needs warming up, how much jam I have created, how much energy I have wasted, and when and where I should stop. Driven by the need to compensate for the wastage I have generated which I have also meant to critique, I make the next work. I turn to sound, an amazing by-product of my excessive, doomed-to-fail generative circuit machine.
                        <br>The circuit system I have made gives off patterns of sound as a result of the domino effect of the bridging-up connections processing. These sounds, generated by electronics in the circuit, and the mechanically accumulated delay time are valuable to me. This machine of mine is no longer as monotonous as it looks on paper. The apparent ‘waste’ and ‘excess’ force open its (often forgotten) functional purpose (i.e. the blackbox of an electronic circuit) to generate a 2nd-generation schematic state. By opening the blackbox of the electronic circuit, I call attention to what lies between the input and output state. It seems the algorithm and intense soldering exercises I have done present a surprising artistic meaning.
                    </p>
                </b-col>
            </b-row>

        </b-container>
           
            
            
    </div>
</template>

<style scoped>

</style>