<template>
    <div class="individual-work-page-container">
       
        <b-container  class="work-session-backgroundcolor">
            <b-row>
                <!-- Work Title -->
                <b-col> <h3> {{(WorkInfo[0].title)}}</h3> </b-col>
            </b-row>
            <b-row>
                <b-col>     
                    <!-- Feature Image : -->
                    <b-img  src="~/assets/images/work/hardworkingcircuit10/completeschematic.jpg" fluid > </b-img>
                    <figcaption class="figure-caption"> The sketch v1.0 </figcaption>
                </b-col>
                
            </b-row>
            <b-row>
                
                <b-col md='9' order="1" order-md="2"> 
                    <p>
                        {{(WorkInfo[0].previewText)}} 
                    </p>
                    <h4> hardworking circuit #1</h4>
                   <p>My work is invoked by my dissatisfaction with the overly spectacular appearance and total black-boxing of the algorithm and internal mechanisms in many media art works nowadays.</p>
                   <p>Trained in a media art curriculum, I have a strong, even desperate, urge to maximize the potential of tools and raw materials in my hands, to push them in order to feel their limits. “How dumb can an electronic circuit function?” This question has always been lingering in my mind.  Conventions of circuit design predicate primarily upon functionality and economic return. In response, in hardworking circuit #1, I have created an overtly excessive, and almost unnecessary circuit system, just to turn on some LED lights.</p>
                    <p>I begin with plotting a schema of monotonous, repetitive circuit, using as many units as possible of relay switch to bridge up the sequential extension of cables, merely for the purpose of electricity connection. As I advance the connections and reach the 50th relay switch, the intensifying resistance of the growing cables and disorder in the relay switch cause the whole system to break down. Forced to stop by the circuit I have made, I review the ‘paper concept’ to reconsider what has happened by calculation, measurement and analysis, followed by a series of trial and error.  Numbers and hardware – cold and inhuman they are – tell me a lot: why the system needs warming up, how much jam I have created, how much energy I have wasted, and when and where I should stop. Driven by the need to compensate for the wastage I have generated which I have also meant to critique, I make the next work. I turn to sound, an amazing by-product of my excessive, doomed-to-fail generative circuit machine.</p>
                    <p>The circuit system I have made gives off patterns of sound as a result of the domino effect of the bridging-up connections processing. These sounds, generated by electronics in the circuit, and the mechanically accumulated delay time are valuable to me. This machine of mine is no longer as monotonous as it looks on paper. The apparent ‘waste’ and ‘excess’ force open its (often forgotten) functional purpose (i.e. the blackbox of an electronic circuit) to generate a 2nd-generation schematic state. By opening the blackbox of the electronic circuit, I call attention to what lies between the input and output state. It seems the algorithm and intense soldering exercises I have done present a surprising artistic meaning.    </p> 
                    <h4> 勤力電路＃1 </h4>

                    <p>概念始於對現今媒體藝術的華麗外殼及背後黑盒子運作規則的不滿。</p>

                    <p>一直以來在媒體藝術學院受訓、浮游,絕望的總想把手上的材料和工具推到不知哪一個極限。「電路可以有多愚蠢地運作」是老是常出現在腦海的問題。由於電路的設計似乎多是以經濟效益為原則,我才想製作一個過量、沒必要得顯然易見的電路來開啟一些發光二極管(LED),作為回應先前提及的不滿。</p>

                    <p>首先是繪畫了一個圖面上重複單調的電路圖,在單一電線管道用上了海量的繼電器作為橋樑來延續電線的長度而已。當要把 電路圖變成實體,接駁第五十個繼電器時,愈來愈長的電線內的電阻和繼電器的失效令整個電路「功能」報廢,我不得不停下來審視自己在之前的紙上談兵,從一輪考量實際情況的計算、量度和試錯反省,算式上數字和冰冷的電子零件的姿態在告訴我 更多這件作品的事實:為什麼他們運作前要熱身,製造了多少混帳,浪費了多少能量,而我什麼時候在哪裡就好要停。一時間有感自己根本在製造本來要批判的對象。</p>

                    <p>同一時間我卻又發覺這電路衍生的「副產品」是很有價值的,骨牌般的繼電器聲音有點搔得著耳朵癢處,每個繼電器運作時累積耽擱的時間好像出奇地珍貴。這個電路在實體化後好像沒有本來在紙上的單調。</p>

                    <p>我只是用大量焊接填補了在輸入和輸出中間黑盒子般的轉化法則而已,而這也偶然帶來了一點驚喜的美學 。</p>








 



                </b-col>

                <b-col md="3"> 
                    <p> {{(WorkInfo[0].medium)}} 
                        <br>
                        {{(WorkInfo[0].year)}}
                    </p>                        
                    <hr>
                    <p> <small>tag:</small>
                        <br>
                        {{(WorkInfo[0].category)}}
                    </p>
                </b-col>
            </b-row>

            <!-- WORK CONTENT -->
            <b-row>
                <b-col>
                   <h4>@Sparkle! <a href="https://www.lcsd.gov.hk/CE/Museum/APO/en_US/web/apo/oyip_sparkle_regarding_lightness.html" target="_blank" rel="noopener noreferrer">regarding lightness: On Life's Way </a> 2015 Feb</h4> 
                   <div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/122240196" style="position:absolute;top:0;left:0;width:100%;height:100%;" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>
                    <p><a href="https://vimeo.com/122240196">hardworking circuit #1</a> from <a href="https://vimeo.com/user4910473">wongchunhoi9</a> on <a href="https://vimeo.com">Vimeo</a>.</p>
                    <b-img src="~/assets/images/work/hardworkingcircuit10/hardworkingcircuit1_oi_1.jpg" fluid></b-img>
                    <b-img src="~/assets/images/work/hardworkingcircuit10/hardworkingcircuit1_exhibitionview3.jpg" fluid></b-img>
                    <b-img src="~/assets/images/work/hardworkingcircuit10/hardworkingcircuit1_exhibitionview5.jpg" fluid></b-img>
                    <b-img src="~/assets/images/work/hardworkingcircuit10/hardworkingcircuit1_button.jpg" fluid></b-img>
                    <b-img src="~/assets/images/work/hardworkingcircuit10/hardworkingcircuit1_hloworld.jpg" fluid></b-img>
                    <p>"hellow world" GOBO</p>
                    <b-img src="~/assets/images/work/hardworkingcircuit10/hardworkingcircuit1_hiddenpart.jpg" fluid></b-img>
                    <p> on the ceiling</p> 
                    


                </b-col>
            </b-row>

            <b-row>
                <b-col>
                    <h4>The Prototype</h4>
                       <div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/114019383" style="position:absolute;top:0;left:0;width:100%;height:100%;" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>
                        <p><a href="https://vimeo.com/114019383">hardworking circuit 1 DEMO 20141209</a> from <a href="https://vimeo.com/user4910473">wongchunhoi9</a> on <a href="https://vimeo.com">Vimeo</a>.</p>  

                        <b-img src="~/assets/images/work/hardworkingcircuit10/hardworking-circuit-1-view-1.jpg" fluid></b-img>
                        <b-img src="~/assets/images/work/hardworkingcircuit10/hardworking-circuit-1-view-2.jpg" fluid></b-img>
                        <b-img src="~/assets/images/work/hardworkingcircuit10/hardworkingcircuit1_workinprogress_2.jpg" fluid></b-img>
                        <b-img src="~/assets/images/blog/2-Prototype-set-up-draft-20140914.jpg" fluid thumbnail></b-img>
                        
                </b-col>
            </b-row>
               
            <b-row>
                   <b-col>
                    <h4>the sketches and calculation</h4>
                    
                        <b-img src="~/assets/images/work/hardworkingcircuit10/completeschematic.jpg" fluid></b-img>
                    
                    
                        <b-img src="~assets/images/work/hardworkingcircuit10/hardworkingcircuit1_limiting-calculation.jpg" fluid></b-img>
                    
                        <b-img src="~/assets/images/work/hardworkingcircuit10/hardworkingcircuit1_schematic.jpg" fluid></b-img>
                    
                   </b-col>
            </b-row>

            <b-row>
                <b-col >
                    <h3 class="very-important" >very important debug:</h3>

                    <b-img src="~/assets/images/work/hardworkingcircuit10/hwcimprove_1.jpg" fluid></b-img>
                </b-col>
            </b-row>
                  
            <b-row>
                <b-col>
                    <div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/191432282" style="position:absolute;top:0;left:0;width:100%;height:100%;" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>
                    <p><a href="https://vimeo.com/191432282">hardworking circuit 1.0  @ hardworking burning electricity</a> from <a href="https://vimeo.com/user4910473">wongchunhoi9</a> on <a href="https://vimeo.com">Vimeo</a>.</p>

                    <div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/191433435" style="position:absolute;top:0;left:0;width:100%;height:100%;" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>
                    <p><a href="https://vimeo.com/191433435">hardworking circuit 1.0 @ hardworking burning electricity light bulb</a> from <a href="https://vimeo.com/user4910473">wongchunhoi9</a> on <a href="https://vimeo.com">Vimeo</a>.</p>

                    
                </b-col>
            </b-row>


        </b-container>
           
            
            
    </div>
</template>

<script>
export default {
    data() {
        return {
            WorkInfo: [
                {
                    id: 'hardworking-circuit-1-0',
                    title: "hardworking circuit #1.0 勤力電路＃1.0", 
                    previewText: "",
                    thumbnail:
                        "hardworking-circuit-1-sketch.svg",
                    medium:"electronics | installation",
                    year:"2014",
                    category: "electronics | installation |  "
                }
            ]
        }
    },
    head() {
        return{
            title: this.WorkInfo[0].title,
            meta: [
                { hid: 'description', name: this.WorkInfo[0].title , content: this.WorkInfo[0].previewText },
                { hid: 'keywords', name: this.WorkInfo[0].medium , content: this.WorkInfo[0].category }
      
            ]
        }
    }
}
</script>

<style scoped>
.very-important {
    color: red;
    letter-spacing: 3px;

}

.scroll-container { 
    overflow: auto;
  white-space: nowrap;
  padding: 2px;
  height: auto;
  
}
</style>