<template>
    <div class="individual-work-page-container">
       
        <b-container fluid class="work-session-backgroundcolor" style="max-width: 1300px;">
            <b-row>
                <!-- Work Title -->
                <b-col> <h3> {{(WorkInfo[0].title)}}</h3> </b-col>
            </b-row>
            <b-row>
                <b-col>     
                    <!-- Feature Image : -->
                   
                    <b-embed
                        type="iframe"
                        aspect="16by9"
                        src="https://www.youtube.com/embed/xHXBLSxWkPk"
                        allowfullscreen
                    ></b-embed>
                    
                    <figcaption class="figure-caption"> swift the circuit </figcaption>
                </b-col>
                
            </b-row>
            <b-row>
                
                <b-col md='9' order="1" order-md="2"> 
                    <p>
                        {{(WorkInfo[0].previewText)}} 
                    </p>
                    <h5>關鍵詞 keywords：</h5>
                        
                    <p>
                        畫面的格數；慣性作為推動力；開關作為書寫的行動；交流電流作為待發的種子；亂數發生器的硬體；電路；二進邏輯；可數算的迴圈；發條裝置；不可預測的時差 frame rate, Real-time experiments, opening the black box, re-activating the reception location, deconstructing cinema, reconstructing cinema, sequential ordering and random ordering, AC as artistic raw material, visualizing mathematical concepts, algorithm, ensemble cinema, overtone, harmonic, montage, custom-made software, art from data, auditory fingerprints, continuity, inertia turned into force, an on-off switch as a writing tool, hardware random number generator, simple electrical circuit, binary Logic, countable loops, unpredictable clockwork by time difference
                    </p>

                    <h5>勤力電路1.4 – 開著了的投影機 (持續創作)》 </h5>
                    
                    <p>王鎮海的裝置作品《勤力電路》是一個以繼電器串連的系統。繼電器是以電力操控的開關，當電流通過銅線，銅線產生磁場閉合繼電器中的電路，組成電流傳輸的橋樑，繼而觸發下一個繼電器。觀眾可透過手動開關，自由操控骨牌似的電路系列。《勤力電路1.4》以藝術家之前的創作《勤力電路1》作為骨幹。作品結構以多個繼電器串聯而成，並以骨牌的形式相繼啟動，一個接一個，直到終端電器被開啟。重覆設置於電路上的繼電器具電子時計的作用，最後被選擇啟動的電器是藝術性和趣味的關鍵。開關按鈕後觸發的每一個步驟相對於電影的情節，像微敍事，觀眾觀看著電力飛舞的定格及藝術家舖墊的最終結局。電力在媒體藝術是必然的存在，王氏再一次以電力為藝術的原材料，並呈現電力在不同物理形式上的操控。</p>

                    <p>在《勤力電路#1》、《勤力電路#1.1》、和《勤力電路#1.2》中，電路系統雖然有著不同設計，但電路最終都只為傳輸電流，以啟動瑣碎物件，如一顆小型LED燈、一隻以摩打驅動的玩具魚、一個改裝音樂盒等。透過改變平日的電路流程，耗時又吃力的勤力電路希望提升人類對尋常瑣物的興趣。王氏稱這些終端物件為系統的結局。當繼電系統開始運作，一連串的動作隨繼電過程而觸發，終端物亦最終受改變。王氏所設計的結局，如閃動的燈和震動的魚，吸引人們的目光，直至過程終結。王氏一直持續研究不同電子零件以製造不同的結局。技術上，將大部分的備開關的電器放置於電路上任何繼電的一點，都能被「啟動」。</p>

                    <p>電流訊號的流動是耗時的過程。在版本1.4 中，作品強調繼電過程的時限及持續時間。以《勤力電路1.2》為例，每4.5 秒，電流平均通過360 個繼電開關。這是藝術家展開勤力電路最新版本的基礎。最新版本中，電路上1秒能把80個繼電器逐一啟動。這種計算連繫到我們對電影時間的認知，由傳統以1秒24格為標準的菲林影片徹底改變成一部1秒80幀的影像投影機。對此王氏以電影作典故，並嘗試在概念上開拓其形式。問題亦繼續延續下去：觀眾如何體驗這個1 秒80 格的視覺呈示？觀眾如何描敍在作品中的時間經驗？在眾多的5 秒繼電故事裡，觀眾得到了什麼？他們在連續而無間斷的5 秒情節入面，會建構出怎樣的故事？</p>

                    <hr>
                    <hr>

                    <p>王鎮海的《勤力電路1.4 ‒ 開著了的投影機 (持續創作)》把交流電化作電影的素材。作品以多個繼電器串聯而成，骨牌式的接連啟動，直到沿途各個終端電器被開啟。開關按鈕開啟，數秒間近百個繼電器逐個啟動，近似傳統投影機每秒鐘運行24格菲林般，只是王的作品的「數秒」卻重新喚召訪者的好奇 – 到底「數秒」有多長？「數秒」所盛載的微細過程和精巧描述有甚麼可能？訪者觀看著電力飛舞間斷的座落於藝術家隨心設定的多個落點以至最後「終局」。王鎮海所安排的電「路」書寫著具時間性的流程，帶鮮明的起承轉合，是絕不苟且的微敘事。故事呢？就由觀者自行想像了。</p>

                    <p> 《勤力電路》（2015）在油街和「據點。句點」開始實驗發表，漸進成持續的系列。《勤力電路1.3》曾獲2018年ifva比賽媒體藝術組金獎，其中評審高士強稱讚道：「（作品）把從起點到終點的過程不斷延遲，跟我們的生活經驗有一點的切合。他把過程延遲，就像電影中的特寫鏡頭，把這過程放大，形成特別深刻的意義。」</p>

                    <h5>Wong Chun-hoi’s hardworking circuit #1.4 – A switched-on projector [work-in-progress] (2018)</h5>
                    <p>A circuit physically functions as a sequence of successive on-off switches that form a domino structure. A bunch of switches, turned on sequentially in serial ordering, will “terminate” after turning on all electronic/everyday objects one by one. The selection of objects to be turned on the sequence is the key to discovering the playful artistic possibilities afforded by the timeframe generated by the circuit’s physical manifestation. Each iteration, ignited by pressing the “on” button, initiates a process comparable to a movie sequence unfolding in the form of x frames per second, like a micro narrative, whereby the audience study the causal drama of electricity dancing through within a set timeframe with a visible, spectacular process and a curious “denouement” [結局、終局].</p>

                    <p>The repetitive relay designed into the circuit ends with an electronic clock, the “denouement,” whereas the conspicuous objects along the relay are suggested or revealed on a TV monitor connected to hidden web cams in various parts of the venue. While electricity has always been taken for granted in media art, Wong takes up electricity as an artistic raw material, to perform its manifestation in many physical forms.It takes several seconds to turn on all sections of relay successively one by one. With this, Wong preserves his work’s allusion to cinema in a conceptually expanded form. The question remains: how do visitors experience this procedural visual presentation? How would they describe their experience of time in this work? What would visitors get out of each of the many 5-second relay narratives in the show? And what about a narrative they may construct on the spot with many continuous, consecutive 5-second segments?</p>

                    <p>The hardworking circuit series began in 2015 as experiments, published at Oil Street and the Floating Projects. hardworking circuit 1.3 has won the Gold Award, Media Art category in the ifva 2018 competition. Gao Shiqiang, one of the jurors, commented, “This artist attempts to delay the completion of the route from A to B, and makes something out of this clever idea. The root itself is very complicated, and reflects what our daily lives are about, that you often have to go through a lot of things before you get to the final destination.”</p>

                    <hr>
                    <h5>Exhibition Record</h5>
                    <p><a href="https://www.writingmachine-collective.net/wordpress/wmc_e6/" target="_blank" rel="noopener noreferrer">【文字機器創作集第六輯 WMC_e6】</a>
                    <br>
                    <a href="https://www.writingmachine-collective.net/wordpress/wmc_e6_p22_open-this-friday_running-walking/" target="_blank" rel="noopener noreferrer">“Running, walking, jogging along a timeline with the same speed” by Wong Chun-hoi and Hugo Yeung 假如速度與跑姿換腳幅度無關</a></p>
                    
                </b-col>

                <b-col md="3"> 
                    <p> {{(WorkInfo[0].medium)}} 
                        <br>
                        {{(WorkInfo[0].year)}}
                    </p>                        
                    <hr>
                    <p> <small>tag:</small>
                        <br>
                        {{(WorkInfo[0].category)}}
                    </p>
                </b-col>
            </b-row>

            <!-- WORK CONTENT -->

                
            <b-row>
                <b-col>
                    <h4>Instllation Set</h4>
                    <h5>I feel very difficult to explain and make documentation</h5>
                    <b-embed
                        type="iframe"
                        aspect="16by9"
                        src="https://www.youtube.com/embed/02gnfnO_pGg"
                        allowfullscreen
                    ></b-embed>
                    <hr>
                    <h5>please take a quick look on the space</h5>
                    <b-embed
                        type="iframe"
                        aspect="16by9"
                        src="https://www.youtube.com/embed/3KwEVJS7svw"
                        allowfullscreen
                    ></b-embed>

                    <b-img src="~/assets/images/work/hardworkingcircuit14/1K4A1027.jpg"  thumbnail fluid> </b-img>
                    <br>
                    
                </b-col>
            </b-row>

            <b-row>
                <b-col>
                    <h4>more detail set up Components</h4>

                    <h5>First we go through all the components when they are static</h5>
                    <b-embed
                        type="iframe"
                        aspect="16by9"
                        src="https://www.youtube.com/embed/IJZO44oW4RI"
                        allowfullscreen
                    ></b-embed>
                </b-col>
            </b-row>

            <b-row>
                <b-col md="7">
                    <b-embed
                        type="iframe"
                        aspect="16by9"
                        src="https://www.youtube.com/embed/N_K2Ppzp8rw"
                        allowfullscreen
                    ></b-embed>
                </b-col>
                <b-col md="5">
                    Stop watch
                    <b-img src="~/assets/images/work/hardworkingcircuit14/hwc4-stopwatch.jpg"  thumbnail fluid> </b-img>
                </b-col>
            </b-row>
            <b-row>
                <b-col md="7">
                    <b-embed
                        type="iframe"
                        aspect="16by9"
                        src="https://www.youtube.com/embed/JjSK52HJHwA"
                        allowfullscreen
                    ></b-embed>
                </b-col>
                <b-col md="5">
                    This is the position where you should be able to access the on/off button
                    <b-img src="~/assets/images/work/hardworkingcircuit14/hwc4-startingset.jpg"  thumbnail fluid> </b-img>
                </b-col>
            </b-row>

            <b-row>
                <b-col md="7">
                    <b-embed
                        type="iframe"
                        aspect="16by9"
                        src="https://www.youtube.com/embed/QCJU8zVCddw"
                        allowfullscreen
                    ></b-embed>
                </b-col>
                <b-col md="5">
                    A closer look CCTV monitor.  There are 4 channels of unknown video clips that show the live feed of some camera image capture along the circuit
                </b-col>
            </b-row>

            <b-row>
                <b-col md="7">
                    <b-embed
                        type="iframe"
                        aspect="16by9"
                        src="https://www.youtube.com/embed/kLwEPnmR1nQ"
                        allowfullscreen
                    ></b-embed>
                </b-col>
                <b-col md="5">
                    Then here's start the relay sequence
                </b-col>
            </b-row>

            <b-row>
                <b-col md="7">
                    <b-embed
                        type="iframe"
                        aspect="16by9"
                        src="https://www.youtube.com/embed/6woOqmFhcj4"
                        allowfullscreen
                    ></b-embed>
                </b-col>
                <b-col md="5">
                    a closer look on the circular relay sequence on floor, there's a motor inside
                </b-col>
            </b-row>

            <b-row>
                <b-col md="7">
                    <b-embed
                        type="iframe"
                        aspect="16by9"
                        src="https://www.youtube.com/embed/hbyYavIu0Y0"
                        allowfullscreen
                    ></b-embed>
                </b-col>
                <b-col md="5">
                    on the wall side, here's a series of synchrozing motors. Each motors has a acylic strip attached on the rotation axis that swing like a clock ?
                </b-col>
            </b-row>
            
            <b-row>
                <b-col md="7">
                    <b-embed
                        type="iframe"
                        aspect="16by9"
                        src="https://www.youtube.com/embed/vGtO-AY-nvE"
                        allowfullscreen
                    ></b-embed>
                </b-col>
                <b-col md="5">
                    the relay sequence circuit continue along the wall. Here's the 2nd part of the wall.
                </b-col>
            </b-row>

            <b-row>
                <b-col md="7">
                    <b-embed
                        type="iframe"
                        aspect="16by9"
                        src="https://www.youtube.com/embed/IhJNFxCZpeE"
                        allowfullscreen
                    ></b-embed>
                </b-col>
                <b-col md="5">
                    A camera is pointing to a toy fish on floor. While the pink toy fish occasinally flip its tail
                </b-col>
            </b-row>

            <b-row>
                <b-col md="7">
                    <b-embed
                        type="iframe"
                        aspect="16by9"
                        src="https://www.youtube.com/embed/jUyOcJAX7AI"
                        allowfullscreen
                    ></b-embed>
                </b-col>
                <b-col md="5">
                    towards the end of this wall (right hand side), A sheep sound noise maker toy is rotated by a motor.
                </b-col>
            </b-row>

           

            <b-row>
                <b-col md="7">
                    <b-embed
                        type="iframe"
                        aspect="16by9"
                        src="https://www.youtube.com/embed/yHrW7chosk8"
                        allowfullscreen
                    ></b-embed>
                </b-col>
                <b-col md="5">
                    the relay circuit continues......
                </b-col>
            </b-row>

            <b-row>
                <b-col md="7">
                    <b-embed
                        type="iframe"
                        aspect="16by9"
                        src="https://www.youtube.com/embed/v8GuyPhFhPw"
                        allowfullscreen
                    ></b-embed>
                </b-col>
                <b-col md="5">
                    when the electricity trigger reach the kitchen, it turns on a tripple (or double?) pendulum that drived by a almost-malfunctioned stepper motor. Another camera is pointing to this pendulum as well.
                
                </b-col>
            </b-row>

                  <b-row>
                <b-col md="7">
                    <b-embed
                        type="iframe"
                        aspect="16by9"
                        src="https://www.youtube.com/embed/Qy1t-SEcj9M"
                        allowfullscreen
                    ></b-embed>
                </b-col>
                <b-col md="5">
                    it comes back to the room. A camera is pointing to the relays
                </b-col>
            </b-row>

                  <b-row>
                <b-col md="7">
                    <b-embed
                        type="iframe"
                        aspect="16by9"
                        src="https://www.youtube.com/embed/OJm4c6xVz_o"
                        allowfullscreen
                    ></b-embed>
                </b-col>
                <b-col md="5">
                    how the relays push forward ... almost to the end
                </b-col>
            </b-row>

                  <b-row>
                <b-col md="7">
                    <b-embed
                        type="iframe"
                        aspect="16by9"
                        src="https://www.youtube.com/embed/Xu4-0cGQ55s"
                        allowfullscreen
                    ></b-embed>
                </b-col>
                <b-col md="5">
                   another angle
                </b-col>
            </b-row>

            <b-row>
                <b-col md="7">
                    <b-embed
                        type="iframe"
                        aspect="16by9"
                        src="https://www.youtube.com/embed/EeuV9Sw61tM"
                        allowfullscreen
                    ></b-embed>
                </b-col>
                <b-col md="5">
                   Tally Counter , it is indeed drived by a string that attached to a solenoid.   +1 when the electricital reach to the end of the circuit. Yes.  That's the end point triggering #1.
                </b-col>
            </b-row>

            <b-row>
                <b-col md="7">
                    <b-embed
                        type="iframe"
                        aspect="16by9"
                        src="https://www.youtube.com/embed/0MsEVZ_uSck"
                        allowfullscreen
                    ></b-embed>
                </b-col>
                <b-col md="5">
                   Close up on the flip clock that hacked by a stepper motor.   I pasted a flipping animation sequence on the clock.  (60 frames  [#00-#59]). This is trying to show how the electricity flow.
                </b-col>
            </b-row>

            <b-row>
                <b-col md="7">
                    <b-embed
                        type="iframe"
                        aspect="16by9"
                        src="https://www.youtube.com/embed/RWtmaiWZ5zU"
                        allowfullscreen
                    ></b-embed>
                </b-col>
                <b-col md="5">
                  Last ending triggering (#3): I hacked a spinning Gym toy. When it is triggered, it is like you press the yellow button on that toy.
                  <b-img src="~/assets/images/work/hardworkingcircuit14/hwc4-gymtoy.jpg"  thumbnail fluid> </b-img>
                  <b-img src="~/assets/images/work/hardworkingcircuit14/hwc4-gymtoymoving.jpg"  thumbnail fluid> </b-img>
                </b-col>
            </b-row>

            

            <b-row>
                <b-col>
                    <h4>Idea Sketch</h4>
                    <b-img src="~/assets/images/hardworking-circuit-1-4-conceptsketch.svg" fluid></b-img>
                    <b-img src="~/assets/images/work/hardworkingcircuit14/hardworking_circuit_1_4_case1.svg" fluid></b-img>
                    <b-img src="~/assets/images/work/hardworkingcircuit14/hardworking_circuit_1_4_case2_motor.svg" fluid></b-img>
                    <b-img src="~/assets/images/work/hardworkingcircuit14/hwc14-part1-synnmotor-1.svg" fluid-grow></b-img>
                    <b-img src="~/assets/images/work/hardworkingcircuit14/hwc14-part1-synnmotor-2.svg" fluid-grow></b-img>
                    <b-img src="~/assets/images/work/hardworkingcircuit14/part 2-01.svg" fluid></b-img>

                </b-col>
            </b-row>
            <b-row>
                <b-col>
                    <h4>Making Of </h4>
                    <b-img thumbnail src="~/assets/images/work/hardworkingcircuit14/hardworking circuit 1 650x460 version4_15fps_loop.gif" fluid></b-img>
                   <b-embed
                        type="iframe"
                        aspect="16by9"
                        src="https://www.youtube.com/embed/nBv6Izqv3kA"
                        allowfullscreen    
                    ></b-embed>
                    <b-embed
                        type="iframe"
                        aspect="16by9"
                        src="https://www.youtube.com/embed/c15BY4rMkLI"
                        allowfullscreen    
                    ></b-embed>
                    <b-embed
                        type="iframe"
                        aspect="16by9"
                        src="https://www.youtube.com/embed/yOnaUXHsb3U"
                        allowfullscreen    
                    ></b-embed>
                </b-col>
            </b-row>

        </b-container>
           
            
            
    </div>
</template>

<script>
export default {
    data() {
        return {
            WorkInfo: [
                {
                    id: 'hardworking-circuit-1-4',
                    title: "hardworking circuit #1.4 勤力電路＃1.4  A switched-on projector [work-in-progress] (2018)" ,
                    previewText: "",
                    thumbnail:
                        "hardworking-circuit-1-4-conceptsketch.svg",
                    medium:"electronics",
                    year:"2018",
                    category:"installation | electronics | stupid  | toy"
                }
            ]
        }
    },
    head() {
        return{
            title: this.WorkInfo[0].title,
            meta: [
                { hid: 'description', name: this.WorkInfo[0].title , content: this.WorkInfo[0].previewText },
                { hid: 'keywords', name: this.WorkInfo[0].medium , content: this.WorkInfo[0].category }
      
            ]
        }
    }
}
</script>

<style scoped>

